### ISSUE TITLE
Update the example please

### ISSUE THREAD

**Issue by LeoMoonStar** [docusign/passport-docusign#2]

**Comment by LarryKlugerDS** [comment]
Hi,
I'm working on an updated example that uses async/await, promises, etc. I plan to publish it around week of July 30th. Thank you for your interest!

**Comment by LeoMoonStar** [comment]
I somehow find the sample code for configure in this repo is different from that on Passport website. I am just wondering what makes the difference
`passport.use(new LocalStrategy(`
  `      function(username, password, done) {`
    `User.findOne({ username: username }, function (err, user) {`
      `if (err) { return done(err); }`
      `if (!user) {`

`passport.use(new DocusignStrategy({`
    `clientID: DOCUSIGN_INTEGRATOR_KEY,`
    `clientSecret: DOCUSIGN_APP_SECRET,`
    `callbackURL: "http://localhost:3000/auth/docusign/callback"`
  `},`
 ` function(accessToken, refreshToken, profile, cb) {`
   ` User.findOrCreate({ email: profile.email }, function (err, user) {`
     ` return cb(err, user);`
    `});`
 ` }`
`));`

**Comment by LarryKlugerDS** [comment]
https://github.com/docusign/docusign-code-examples/tree/master/node may be of help

**Comment by mmallis87** [comment]
DocuSign uses OAuth2 standard, which is completely different from the so-called "Basic Authentication" (i.e. username/password) that is implemented by LocalStrategy. Facebook have a similar Passport.js implementation, sinc they also use OAuth2: https://github.com/jaredhanson/passport-facebook#configure-strategy
