### ISSUE TITLE
Scope separator: DocuSign expects URL encoded spaces

### ISSUE THREAD

**Issue by jeff00seattle** [docusign/passport-docusign#7]
This is a scoping separator issue that either **DocuSign identity service** or this **passport-docusign module** needs to resolve.

DocuSign identity service handling of scope expects not commas but URL encoded spaces.

I am working on a service that uses DocuSign identity service to authenticate to use CLM, which requires SpringCM scoping:

- `spring_read`
- `spring_write`

It expects the scoping separation to be URL encoded spaces `'%20'.`
`scope=spring_read%20spring_write`

passport-docusign default scope formatted does not work to permit access to SpringCM API using DocuSign access token:
`scope=spring_read%2Cspring_write`

- Not '+'
- Not commas ','
- Not URL encoded commas '%2C'

**Comment by LarryKlugerDS** [comment]
Have you tried setting the Passport OAuth2 options attribute `scopeSeparator` ?

I think you're right that the default setting in [strategy.js](https://github.com/docusign/passport-docusign/blob/master/lib/strategy.js#L54) should be updated to `%20`

But it looks like you can set it explicitly.

**Comment by LarryKlugerDS** [comment]
... And you set the options.scope to an array with your desired scopes.
See [Line 230 of the OAuth2 strategy](https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L230)

**Comment by jeff00seattle** [comment]
@LarryKlugerDS 
DocuSign api documentation lists scopes separated by url-encoded space:
https://developers.docusign.com/orgadmin-api/guides/auth

**Comment by jeff00seattle** [comment]
In order to be able to access DocuSign CLM via SpringCM API v2, it requires a DocuSign access token with scoping: `**spring_read**%20**spring_write**`

If I used `scopeSeparator: ' '`, then it generates:

`&scope=spring_read+spring_write&`

However, the DocuSign generated

**Comment by LarryKlugerDS** [comment]
Hi Jeff! 
Am I right that you fixed this issues with your PRs and added tests?

Thank you very much for your help with this project,
Larry

**Comment by LarryKlugerDS** [comment]
`+` is now supported as a scope separator in addition to `%20`
